// ZH-CN
//
// 区域设置可以为空白，在这种情况下，它将用作默认值
// 中文
//
// 如果您不知道您的语言/当地代码，请在此处填写：
//   https://www.science.co.il/language/Locale-codes.php
var language = 'CN';
var locale = 'CN';

// 在这里翻译！
var translation = {
	"（空注）": "(nota vacia)",
	"（此过程可能需要一段时间，因为我们需要重新加密您的钥匙串）": "",
	"，但是你有{{length}}等待被同步的变化，如果你这样做会失去": "",
	"[制作链接]（https://turtlapp.com）很简单！": "",
	"{{email}}已确认帐户，此邀请将使用其公钥加密。": "",
	"{{email}}有一个Turtl帐户，但尚未确认。您可能需要使用密码来保护邀请，以使其保密。": "",
	"{{email}}未在Turtl注册。建议使用密码来保护邀请，以使其保密。": "",
	"“{{n}}天前”："",
	"{{n}}小时前: "",
	"{{n}}分钟前": "",
	"{{n}}秒前": "",
	"<strong>错误：</ strong> {{errmsg}}（{{errcode}}）": "",
	"关于Turtl如何工作的说明",
	"接受": "Aceptar",
	"添加新书签": "",
	"添加新文件": "",
	"添加新图片": "",
	"添加新笔记": "Añadir una nueva nota",
	"添加新密码": "",
	"添加新的文字说明": "",
	"添加": "Añadir",
	"高级设置": "Ajustes avanzados",
	"所有笔记": "Todas las notas",
	"你确定要删除你的帐户和所有数据<em>永远</ em>吗？": "¿Estás seguro de que quieres eliminar tu cuenta y todos tus datos <em>para siempre</em>?",
	"附上文件": "Adjuntar un archivo",
	"回到我的笔记": "Volver a mis notas",
	"冻结同步阻止。": "",
	"布告栏名称": "Título del tablón",
	"Boards": "Tablones",
	"书签": "marcador",
	"书签": "Marcador",
	"取消": "Cancelar",
	"更改登录名": "",
	"更改密码": "Cambiar contraseña",
	"更改密码需要连接": "",
	"清除所有当前的过滤器（显示板上的所有注释）": "Limpiar los filtros actuales (muestra todas las notas en el tablón)",
	"清除本地数据并注销": "",
	"清除本地数据": "Limpiar datos locales",
	"客户端版本：<em> {{version}} </ em>": "Versión del cliente: <em>{{version}}</em>",
	"逗号，分开，标签": "coma, separación, etiquetas",
	"在导入之前完全擦除当前配置文件": "",
	"确认密码短语": "Confirmar frase de contraseña",
	"确认您当前的登录信息": "Confirmar tu login actual",
	"确认电子邮件重新发送": "",
	"连接到Turtl服务！脱离离线模式。同步你的个人资料。": "¡Conectado al servicio de Turtl! Desactivando modo offline. Sincronizando tu perfil.",
	"已连接": "",
	"无法连接到服务器": "No se ha podido conectar con el servidor",
	"创建一个新帐户以将数据迁移到。": "",
	"创造一个空间": "",
	"创建一个帐户": "Crear una cuenta",
	"在{{space}}中创建电路板": "",
	"创造日期": "Fecha de creación",
	"创造": "Crear",
	"加密错误": "Error criptográfico",
	"当前电子邮件": "",
	"当前密码短语": "Frase de contraseña actual",
	"破折号</ li> <li>制作</ li> <li>子弹": "guiones</li><li>forman</li><li>puntos",
	"破折号 - 制造<br>  - 子弹": "",
	"调试信息": "Información de debug",
	"调试日志": "",
	"解密{{percent}}项": "",
	"删除帐户": "Eliminar cuenta",
	"删除当前注释": "Eliminar nota actual",
	"删除我的帐户": "Eliminar mi cuenta",
	"删除同步项目": "",
	"删除此板": "",
	"删除此空间＆raquo;": "",
	"删除": "Eliminar",
	"脱离Turtl服务。参与离线模式。您的更改将被保存并重新同步一次！": "Desconectado del servicio de Turtl. Activando modo offline. ¡Tus cambios serán guardados y sincronizados cuando vuelvas a estar online!",
	"正在下载文件...": "",
	"编辑板": "",
	"编辑当前音符": "Editar nota actual",
	"编辑说明": "Editar nota",
	"编辑": "Editar",
	"正在修改{{title}}": "Editando {{title}}",
	"在markdown中编辑": "Editar en markdown",
	"电子邮件地址": "",
	"电子邮件": "",
	"输入新的电子邮件/密码": "",
	"加载配置文件时出错": "Error cargando perfil",
	"错误": "",
	"优秀": "excelente",
	"出口": "",
	"反馈": "Feedback",
	"文件保存到下载/ {{filename}}": "",
	"文件": "archivo",
	"文件": "Archivo",
	"下载文件，解密个人资料......": "",
	"通过点击<kbd> / </ kbd>并输入搜索，然后键入<kbd> Enter </ kbd>来查找注释。 注释搜索框支持 <a href=\"https://sqlite.org/fts3.html#full_text_index_queries\" target=\"_blank\">Sqlite's FTS3 syntax</a>.": "",
	"格式化帮助": "Ayuda de formato",
	"来自{{user}} ": "",
	"冻结 - 此项目阻止同步。通过解冻或删除修复": "",
	"给我们反馈": "Danos feedback",
	"提供反馈": "Danos tu feedback",
	"好": "buena",
	"Grabbed {{num_keychain}}钥匙串条目，{{num_boards}}板，{{num_notes}}条记录，{{num_files}}来自旧服务器": "",
	"伟大的": "muy buena",
	"有想法吗？有问题吗？": "¿Tienes una idea? ¿Un problema?",
	"这是一张图片：": "Aquí tienes una imagen: ",
	"这是一张图片<br>![](https://turtlapp.com/images<space> </space>/favicon.png)": "",
	"我会记住我的登录信息！": "¡Me acordaré de mi login!",
	"图片网址": "",
	"图片": "imagen",
	"图片": "Imagen",
	"进口和出口": "",
	"导入所有内容，覆盖当前项目": "",
	"导入的{{count}}项": "",
	"索引笔记": "Indexando notas",
	"初始化Turtl": "Inicializando Turtl",
	"邀请密码短语": "",
	"邀请标题（与被邀请者共享）": "",
	"邀请参加”{{board_title}}＆quot;": "Invitar a &quot;{{board_title}}&quot;",
	"邀请": "Invitar",
	"受邀者的电子邮件地址": "Correo del invitado",
	"看起来您在迁移过程中遇到了一些问题。请不要担心，您的数据在旧Turtl服务器上仍然是安全的，您可以随时重试。请将此日志发送到t {{email}} ”的turtl团队。": "",
	"加入": "Unirse",
	"只是确定......你真的想要删除你的帐户吗？": "Sólo para estar seguros... ¿De verdad quieres borrar tu cuenta?",
	"键盘快捷键": "Atajos de teclado",
	"最后编辑": "Última edición",
	"留下这个空间＆raquo;": "",
	"留下这个空间": "",
	"离开空间需要连接到Turtl服务器": "",
	"加载一切（可能很慢）": "",
	"加载最后{{lines}}行": "",
	"正在加载说明...... ": "",
	"装载简介": "Cargando perfil",
	"退出": "Desloguearte",
	"登录失败": "Logueo fallido",
	"登录现有帐户t": "Loguéate en una cuenta existente",
	"登录": "Loguéate",
	"退出": "Desloguearte",
	"制作链接</a>很简单": "Hacer enlaces</a> es fácil!",
	"成员": "",
	"迁移您的帐户": "",
	"迁移": "",
	"迁移错误......": "",
	"迁移报告": "",
	"迁移开始了。这可能需要几分钟！请耐心等待。": "",
	"把板移到另一个空间": "",
	"将笔记移到另一个空间": "",
	"移动空间": "",
	"移动": "",
	"新书签": "",
	"新电子邮件地址": "",
	"新邮件": "",
	"新邀请": "Nueva invitación",
	"新密码": "Nueva frase de contraseña",
	"下一个": "Siguiente",
	"没有选择布告栏": "",
	"没有发现任何笔记。": "No se han encontrado notas.",
	"这里没有注释！": "¡Aquí no hay notas!",
	"无": "",
	"注意移动成功。": "",
	"笔记预览": "Previsualización de la nota",
	"注意文字": "Nota de texto",
	"请注意，当您将布告栏移动到另一个空间时，它的所有内容都会随之移动。": "",
	"离线模式": "Modo offline",
	"好的": "ok",
	"加载旧配置文件，转换为新格式......": "",
	"老Turtl服务器": "",
	"一个哈希创建一个大标题": "Una almohadilla hace un título grande",
	"只导入当前个人资料中缺少的项目": "",
	"点击<kbd> s </ kbd>轻松打开一个空格，输入你想要的空间名称，然后按<kbd> Enter </ kbd>。然后你将被带到布告栏选择器。点击<kbd>再次输入</ kbd>以显示“所有注释”或输入要打开的板的名称，然后按<kbd> Enter </ kbd>将其打开。": "",
	"打开布告栏菜单": "",
	"打开当前注释": "Abrir nota actual",
	"开放空间菜单": "",
	"点击<kbd> b </ kbd>打开布告栏选择器。你可以点击<kbd> Enter </ kbd>，搜索框为空，打开\” All notes \“或者你可以输入你的布告栏名称想要点击<kbd>输入</ kbd>打开它。": "",
	"或": "O",
	"密码短语（可选）": "",
	"密码短语（可选，但推荐）": "",
	"密码强度：": "Fuerza de la frase de contraseña",
	"Passphrase": "Frase de contraseña",
	"密码": "contraseña",
	"密码": "Contraseña",
	"待邀请": "Invitaciones pendientes",
	"请输入一些反馈意见": "Por favor, escribe algún feedback",
	"请给你的邀请一个标题。": "",
	"请为此用户选择一个角色。": "",
	"上一篇": "Ante",
	"用插入符号引用文字": "Cita texto con un símbolo de intercalación (^)",
	"阅读更多＆raquo; ": "",
	"了解有关<a href=\"https://guides.github.com/features/mastering-markdown/\" target=\"_blank\">markdown</a>.": "",
	"准备同步”": "",
	"真的删除这个布告栏及其所有笔记": "",
	"真的删除这个邀请？": "",
	"真的删除这个笔记": "¿Eliminar esta nota?",
	"真的删除这个空间及其所有数据（布告栏和笔记）？?": "",
	"真的删除这个同步项吗？这样做会撤消你在本地做出的改变（首先尝试解冻）。": "",
	"真的从这个空间删除这个用户？": "",
	"真的将这个空间的所有权交给另一个成员吗？（你将被降级为管理员）": "",
	"真的离开这个空间？": "",
	"删除附件": "Eliminar adjunto",
	"重新发送确认": "",
	"重置搜索": "",
	"重试": "Reintentar",
	"保存": "Guardar",
	"搜索布告栏": "Buscar tablones",
	"搜索空间": "",
	"搜索笔记（{{num}}）": "Buscar notas ({{num}})",
	"搜索笔记": "Buscar notas",
	"选择一块布告栏": "",
	"选择此空间的颜色": "",
	"选择要移动的空间：": "",
	"发送": "Enviar",
	"发送邀请需要连接到Turtl服务器。": "",
	"发送反馈需要连接到Turtl服务器。": "Necesitas una conexión con el servidor de Turtl para poder enviar tu feedback.",
	"设为所有者": "",
	"将此设置为默认空间": "",
	"设置": "",
	"分享这个空间＆raquo;": "",
	"分享这个空间": "",
	"分享": "Compartiendo",
	"显示所有标签": "Mostrar todas las etiquetas",
	"显示此帮助": "Mostrar esta ayuda",
	"空间标题": "",
	"保持登录状态n": "Mantenerse logueado",
	"保持登录状态可能会影响您帐户的安全性。": "",
	"已成功导入{{count}}项！": "",
	"同步信息": "",
	"标签笔记": "Etiquetar nota",
	"点击<em> + </ em>开始": "Pulsa <em>+</em> para empezar",
	"文字说明": "nota de texto",
	"文字说明": "Nota de texto",
	"文字搜索": "Buscar texto",
	"谢谢！": "¡Gracias!",
	"那块布告栏似乎不存在": "Parece que ese tablón no existe",
	"那个密码无效。": "Esa frase de contraseña da grima.",
	"给出的电子邮件无效。": "",
	"指定的角色不存在。": "",
	"接受邀请时出现问题。很可能，给出的密码不正确。": "",
	"更改登录时出现问题。我们正在撤消更改": "",
	"清除你的个人资料时出现了问题": "Ha habido un problema limpiando tu perfil",
	"解密此说明时出现问题。请联系 <a href=\"mailto:info@turtlapp.com\">info@turtlapp.com</a> 寻求帮助。": "",
	"删除该邀请时出现问题": "",
	"删除同步项时出现问题": "",
	"删除用户时出现问题": "",
	"删除你的帐户时出现问题。请再试一次。": "Ha habido un problema borrando tu cuenta. Por favor, inténtalo de nuevo.",
	"删除你的布告栏时出现问题：{{message}}": "Ha habido un problema borrando tu tablón: {{message}}",
	"删除你的笔记时出现了问题：{{err}} ": "Ha habido un problema borrando tu nota: {{err}}",
	"删除空间时出现问题：{{message}}": "",
	"编辑用户时出现问题": "",
	"离开空间有一个问题": "",
	"加载调试日志时出现问题": "",
	"加载时出现问题：": "",
	"迁移该帐户时出现问题": "",
	"移动那个布告栏有问题。": "",
	"移动那张笔记本有问题。": "",
	"打开那个文件时出现问题": "Ha habido un problema abriendo ese archivo",
	"重新发送确认电子邮件时出现问题": "",
	"保存这个帐户存在问题": "Ha habido un problema guardando esa cuenta",
	"保存文件{{filename}}时出现问题。": "",
	"发送反馈时出现问题": "",
	"发送邀请时出现问题": "Ha habido un problema enviando esa invitación",
	"设置API端点时出现问题。尝试重新启动应用程序。": "",
	"设置新所有者时出现问题": "",
	"有一个问题解冻了同步项": "",
	"更新那个布告栏时遇到了一个问题": "Ha habido un problema actualizando ese tablón",
	"更新那个笔记时出现了问题": "Ha habido un problema actualizando esa nota",
	"更新该空间时出现问题": "",
	"你的个人资料的初始负载出现了问题。请再试一次。": "Ha habido un problema con la carga inicial de tu perfil. Por favor, inténtalo más tarde.",
	"同步本地更改时出错，暂停同步。点击打开同步设置并修复＆raquo;": "",
	"此邀请是受密码保护的。您必须输入正确的密码来解锁它。": "",
	"这是你的最后一个空间，不能删除。": "",
	"本说明属于这些布告栏：": "Esta nota pertenece a estos tablones:",
	"这张笔记有未保存的更改。真的离开？": "Esta nota tiene cambios sin guardar. ¿Seguro que quieres salir?",
	"这张笔记不在任何布告栏上。": "Esta nota no está en ningún tablón.",
	"此密码短语用于加密邀请。您可以通过安全渠道（面对面，加密电子邮件，加密聊天等）将其传达给被邀请者。": "Esta frase de contraseña será usada para encriptar la invitación. Puedes enviársela al invitado a través de un canal seguro (en persona, correo encriptado, chat encriptado, etc).",
	"这个过程可能需要一段时间。: "",
	"这个空间与你分享": "",
	"此网址已在{{ids_length}}注释中添加了书签": "Esta URL ya esta como marcador en {{ids_length}} notas",
	"此URL已在另一个注释中添加了书签": "Esta URL ya esta guardada en otro marcador",
	"这将删除您的所有本地数据并将您注销。您下次登录{{msg}}时将再次下载您的个人资料。继续？": "Esto borrará todos tus datos locales y te deslogueará. Tu perfil será descargado de nuevo la próxima vez que te loguees{{msg}}. ¿Continuar?",
	"键盘导航提示": "",
	"标题": "Título",
	"列表": "las lista de cosas que hacer",
	"太短": "muy corta",
	"登录麻烦?": "",
	"Turtl没有”丢失密码“功能。如果你丢失了密码，你的个人资料将永远消失！": "",
	" Turtl笔记使用Markdown，这种格式易于阅读和编写，并且不需要复杂的编辑器。": "Las notas de Turtl usan Markdown, un formato fácil de leer y de escribir que no requiere un complejo editor.",
	"Turtl现在也支持TeX格式。用<code> $$ </ code>开始和结束你的等式": "Turtl también soporta TeX math. Empieza y termina tus ecuaciones con <code>$$</code>:",
	"Turtl服务器": "Servidor de Turtl",
	"用于较小标题的两个哈希": "Dos almohadillas (#) para una cabecera más pequeña",
	"解冻同步项目": "",
	"解锁": "Desbloquear",
	"更新您的登录信息。请耐心等待（不要关闭应用程序）！": "Actualizando tu login. Por favor, ten paciencia (¡Y no cierres la aplicación!)",
	"网址": "URL",
	"Use backticks for `inline_code()`": "Usa comillas de ejecución (`) para `inline_code()`",
	"Use backticks for <code>inline_code()</code>": "Usa comillas de ejecución (`) para <code>inline_code()</code>",
	"用户名": "Nombre de usuario",
	"我们感谢你花时间帮助Turtl做得更好。": "Apreciamos que uses parte de tu tiempo para ayudarnos a mejorar Turtl.",
	"我们不会在任何地方存储您的密码，因此 <em class=\"error\">您需要记住您的密码</em> 或将其保存在安全的地方（如密码管理器）。": "",
	"弱": "débil",
	"欢迎！": "¡Bienvenido!",
	"也有效": "también funcionan",
	"是的，删除我的帐户": "Sí, elimina mi cuenta",
	"你目前处于离线模式。": "Ahora mismo estás en modo desconectado.",
	"你也可以制作文字 __粗体__, *斜体* 或or ~~strikethrough~~.": "También puedes hacer texto __en negrita__, *en cursiva* o ~~tachado~~.",
	"你也可以将文字 <strong>粗体</strong>, <em>斜体</em> 或 <strike>strikethrough</strike>.": "También puedes hacer texto <strong>en negrita</strong>, <em>en cursiva</em> o <strike>tachado</strike>.",
	"你可以制作</li><li>编号的项目</li><li>as well": "también puedes hacer</li><li>listas numeradas</li><li> como estas",
	"you can make<br>1. numbered bullets<br>1. as well": "también puedes hacer <br>1. listas numeradas<br>1. como estas",
	"你没有权限将板/票据移到那个空间。.": "",
	"你没有权限将笔记移动到那个空间。": "",
	"你没有在这个空间上做到这一点所需的许可：{{perm}}": "",
	"你有{{num}}个待定同步项": "",
	"你没有待处理的邀请": "",
	"你有一个或多个冻结的同步项。同步将被卡住，直到你修复它们。首先尝试解冻，如果这不起作用，你可以删除冻结的同步项。": "",
	"你必须连接到Turtl服务才能接受邀请。": "",
	"你必须连接到Turtl服务才能删除邀请。": "",
	"您必须登录才能执行此操作。": "",
	"您必须在接受邀请之前确认您的帐户。如果您不再收到确认电子邮件，可以从”设置“菜单重新发送。": "",
	"在接受邀请之前，您必须先确认自己的帐户。": "",
	"你必须确认你的电子邮件才能共享空间。": "",
	"你必须登录": "",
	"你": "",
	"您的帐户已被删除。": "Tu cuenta ha sido eliminada.",
	"您的帐户需要升级！请输入您的Turtl登录信息。": "",
	"您的帐户密码充当锁定和解锁数据的”密钥“。": "",
	"你的邀请": "",
	"您的登录信息已成功更改！将您退出... ": "",
	"您的登录成功更改！": "¡Tus datos de logueo han sido cambiados correctamente!",
	"你的密码与确认不符。": "Tu frase de contraseña no coincide con la confirmación.",
	"你的设置": "Tus ajustes",
	"你的空间": "",
};

